llm:
  model: "gpt-4o"
  temperature: 0
  streaming: true

database:
  sqlite_uri: "sqlite:///C:/Users/amirb/Desktop/Personal/telecom_company (4).db"
  local_path: "C:/Users/amirb/Desktop/Personal/telecom_company (4).db"

models:
  vanna: "stc_bot"
